services:
  when-app:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
      target: prod
    ports:
      - '3000:3000'
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
      - ./data/public:/app/build/client/public
    restart: unless-stopped

  when-worker:
    build:
      context: ../..
      dockerfile: apps/worker/Dockerfile
      target: prod
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
    restart: unless-stopped

  when-cli:
    build:
      context: ../..
      dockerfile: apps/cli/Dockerfile
      target: prod
    profiles:
      - tools
    stdin_open: true
    tty: true
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
      - ./data/public:/app/build/client/public
