services:
  when-app:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
      target: prod
    platform: linux/amd64
    ports:
      - '3000:3000'
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
      - ./data/public:/app/build/client/public
    restart: unless-stopped

  when-worker:
    build:
      context: ../..
      dockerfile: apps/worker/Dockerfile
      target: prod
    platform: linux/amd64
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
    restart: unless-stopped
