// Frozen argon2id PHC string produced by Bun.password.hash(plaintext, { algorithm: 'argon2id' })
// (Bun 1.3.13, defaults m=65536,t=2,p=1), captured before removing Bun from the project.
// Used to prove @node-rs/argon2 verifies hashes generated by the old Bun-based CLI, so
// existing admin password_hash values in config.yaml keep working without re-hashing.
export const bunArgon2Vector = {
	plaintext: 'when-migration-argon2-vector',
	hash: '$argon2id$v=19$m=65536,t=2,p=1$Jq7XtJRbtuWzd+WqRNabbubk6oxLNWqJ6U9lA/gKJZA$JQmcJnFVezArcfwG4OnSOvtGEgZXnjB+ieIG9tpAGHY'
} as const;
