workspace:
  base: /workspace
  path: src

when:
  - event: push
    branch: main
    path:
      include:
        - ".woodpecker/.web.yml"
        - "apps/web/**"
        - "package.json"
        - "pnpm-workspace.yaml"
        - "pnpm-lock.yaml"
  - event: tag
    ref: "refs/tags/web/v*"

steps:
  prepare:
    image: node:24
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile

  lint:
    image: node:24
    commands:
      - corepack enable
      - cd apps/web
      - touch config.yaml
      - touch .env
      - pnpm run check
      - pnpm run lint

  test:
    image: node:24
    commands:
      - corepack enable
      - cd apps/web
      - pnpm run test
