name: CI (Config Package)

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/config.yml'
      - 'packages/config/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/config.yml'
      - 'packages/config/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm --filter "@when/config..." build

      - name: Lint
        run: pnpm --filter @when/config lint

      - name: Test
        run: pnpm --filter @when/config test:coverage
